@startuml

skinparam componentStyle uml1

database "players"

[PlayerController] --(getPlayerById
[PlayerController] --(savePlayer

[LoginController] --(login

[LoginService] --(getPlayerByUserNameAndPassword
[LoginService] --(getPlayerByEmailAndPassword

[PlayerService] --(getReferencedById
[PlayerService] --(save
[PlayerService] --(findByUserNameOrEmail
[PlayerService] --(findByUserNameAndPassword
[PlayerService] --(findByEmailAndPassword

login -- [LoginService]

getPlayerById -- [PlayerService]
savePlayer -- [PlayerService]
getPlayerByUserNameAndPassword -- [PlayerService]
getPlayerByEmailAndPassword -- [PlayerService]

[PlayerJpaRepository] --("players"
getReferencedById -- [PlayerJpaRepository]
save -- [PlayerJpaRepository]
findByUserNameOrEmail -- [PlayerJpaRepository]
findByUserNameAndPassword -- [PlayerJpaRepository]
findByEmailAndPassword -- [PlayerJpaRepository]

@enduml