@startuml

skinparam componentStyle uml1
skinparam linetype polyline
top to bottom direction

database "matches"

package "Controllers" {
    [MatchController]
}
[MatchController] --(createMatch

package "Services" {
    createMatch -- [MatchService]
}
[MatchService] --(save

package "Repositories" {
    [MatchRepository] --(matches
    save -- [MatchRepository]
}

@enduml