@startuml
skinparam componentStyle uml1
skinparam linetype polyline
top to bottom direction

database "players"

package "Controllers" {
    [PlayerController] --(getPlayerById
    [PlayerController] --(savePlayer
    [PlayerController] --(getPlayerMatches
}

package "Services" {
    [PlayerService] --(getReferenceById
    [PlayerService] --(save
    [PlayerService] --(getMatchesByPlayer

    getPlayerById -- [PlayerService]
    savePlayer -- [PlayerService]
    getPlayerMatches -- [PlayerService]

    [MatchService] -- getMatchesByPlayer
}

package "Repositories" {
    [PlayerJpaRepository] --("players"
    getReferenceById -- [PlayerJpaRepository]
    save -- [PlayerJpaRepository]
}

@enduml